/* Krok – Grammatik: Stufen, Erklärungen, Regeln, Einstiegstest.
   Wird von index.html und tools/validate.js geladen. */
var KROK = { chapters: [] };

/* Grammatik-Leiter */
KROK.stages = [
  {n:1,name:"Präsens",desc:"Konjugation im Präsens"},
  {n:2,name:"Akkusativ",desc:"Das direkte Objekt"},
  {n:3,name:"Genitiv I",desc:"Nach Verneinung und Mengen"},
  {n:4,name:"Verbaspekt",desc:"Imperfektiv oder perfektiv"},
  {n:5,name:"Vergangenheit",desc:"Mit Geschlecht: robiłem / robiłam"},
  {n:6,name:"Instrumental",desc:"jestem projektantem, z mlekiem"},
  {n:7,name:"Lokativ",desc:"w kuchni, o pracy"},
  {n:8,name:"Dativ",desc:"Wem? Komu?"},
  {n:9,name:"Zukunft",desc:"będę robić / zrobię"},
  {n:10,name:"Genitiv II",desc:"Plural und Zahlen"}
];

/* Was ist das? Kurzerklärung je Stufe, mit deutschem und polnischem Beispiel */
KROK.stageInfo = {
  1:{what:"Die Gegenwart. Das Verb ändert seine Endung je nach Person, wie im Deutschen. Das Pronomen (ja, ty …) lässt man im Polnischen meist weg, weil die Endung schon zeigt, wer gemeint ist.",
     ask:"Wer tut es?",
     ex:[["Ich koche. Du kochst.","Gotuję. Gotujesz."],["Wir essen Brot.","Jemy chleb."]]},
  2:{what:"Der 4. Fall. Er markiert das direkte Objekt, also das, worauf sich die Handlung richtet. Im Deutschen ändert sich vor allem der Artikel (der → den), im Polnischen die Endung des Wortes.",
     ask:"Wen oder was?",
     ex:[["Ich trinke den Kaffee.","Piję kawę."],["Ich kaufe einen Fisch.","Kupuję rybę."]]},
  3:{what:"Der 2. Fall. Im Polnischen viel häufiger als im Deutschen: Er steht nach Verneinung, wo das Deutsche den Akkusativ behält, und nach Mengenangaben.",
     ask:"Wessen? Wovon?",
     ex:[["Ich habe keinen Kaffee.","Nie mam kawy."],["ein Glas Wasser","szklanka wody"],["die Küche der Mutter","kuchnia mamy"]]},
  4:{what:"Gibt es im Deutschen nicht als Grammatik. Fast jedes polnische Verb hat zwei Formen: imperfektiv für Vorgang, Gewohnheit oder Wiederholung, perfektiv für ein abgeschlossenes Ergebnis. Im Deutschen drückt man das mit Wörtern wie „gerade“, „immer“ oder „fertig“ aus.",
     ask:"Läuft es noch, oder ist es fertig?",
     ex:[["Ich schreibe gerade einen Brief.","Piszę list."],["Ich schreibe den Brief fertig.","Napiszę list."],["Jeden Morgen trinke ich Kaffee.","Codziennie rano piję kawę."]]},
  5:{what:"Im Polnischen gibt es nur eine Vergangenheitsform statt Perfekt und Präteritum. Die Endung zeigt dabei das Geschlecht der Person: Ein Mann sagt -łem, eine Frau -łam.",
     ask:"Was war?",
     ex:[["Ich habe gekocht. (Mann)","Gotowałem."],["Ich habe gekocht. (Frau)","Gotowałam."],["Sie hat gelesen.","Ona czytała."]]},
  6:{what:"Gibt es im Deutschen nicht. Er steht für das Mittel oder die Begleitung, nach z (mit) und nach być, wenn man sagt, was jemand ist.",
     ask:"Womit? Mit wem? Als was?",
     ex:[["Ich bin Designer.","Jestem projektantem."],["Kaffee mit Milch","kawa z mlekiem"],["Ich fahre mit der Straßenbahn.","Jadę tramwajem."]]},
  7:{what:"Gibt es im Deutschen nicht. Er steht nur nach bestimmten Präpositionen wie w (in), na (auf), o (über) und przy (bei). Im Deutschen steht dort meist der Dativ oder Akkusativ.",
     ask:"Wo? Worüber?",
     ex:[["Wir sind in der Küche.","Jesteśmy w kuchni."],["Wir reden über die Arbeit.","Rozmawiamy o pracy."],["Ich wohne in Hamburg.","Mieszkam w Hamburgu."]]},
  8:{what:"Der 3. Fall, wie im Deutschen. Er markiert, wem etwas gegeben, gesagt oder gezeigt wird.",
     ask:"Wem?",
     ex:[["Ich gebe der Mutter das Buch.","Daję mamie książkę."],["Ich helfe dem Bruder.","Pomagam bratu."]]},
  9:{what:"Es gibt zwei Wege, und der Verbaspekt entscheidet: imperfektiv mit będę + Infinitiv für einen Vorgang, perfektiv einfach in der Präsensform für ein Ergebnis.",
     ask:"Was wird sein?",
     ex:[["Ich werde (eine Weile) kochen.","Będę gotować."],["Ich werde (die Suppe) fertig kochen.","Ugotuję zupę."]]},
  10:{what:"Nach Zahlen ändert sich die Form: Bei 2, 3 und 4 steht der Nominativ Plural, ab 5 der Genitiv Plural. Das gilt auch nach Mengenwörtern wie dużo (viel) und kilka (einige).",
     ask:"Wie viele?",
     ex:[["zwei Äpfel","dwa jabłka"],["fünf Äpfel","pięć jabłek"],["viele Tomaten","dużo pomidorów"]]}
};

/* Regeln für das „Warum?“-Sheet. stage = Stufe der Grammatik-Leiter */
KROK.rules = {
  praes_e:{name:"Präsens: -ę / -esz",stage:1,
    why:"Verben wie pić, gotować und myć bilden das Präsens mit -ę (ich) und -esz (du), er/sie mit -e. Bei Verben auf -ować und -ywać wird daraus -uj-, bei -awać wird -awa- zu -aj-.",
    pattern:"pić → piję, pijesz · gotować → gotuję, gotujesz · przygotowywać → przygotowuję · dodawać → dodaję · brać → biorę"},
  praes_i:{name:"Präsens: -ę / -isz",stage:1,
    why:"Verben auf -ić und -yć bilden ich mit -ę und du mit -isz bzw. -ysz. Das i fällt bei ich oft weg: robić → robię.",
    pattern:"robić → robię, robisz · kroić → kroję, kroisz · smażyć → smażę, smażysz"},
  praes_am:{name:"Präsens: -am / -asz",stage:1,
    why:"Viele Verben auf -ać hängen -am (ich) und -asz (du) direkt an den Stamm.",
    pattern:"mieszać → mieszam, mieszasz · nakrywać → nakrywam · mieć → mam"},
  jesc:{name:"jeść ist unregelmäßig",stage:1,
    why:"jeść folgt keiner der Gruppen. Die sechs Formen lernt man am besten als Reihe.",
    pattern:"ja jem · ty jesz · on je · my jemy · wy jecie · oni jedzą"},
  acc_f:{name:"Akkusativ feminin: -a → -ę",stage:2,
    why:"Das direkte Objekt eines Verbs wie pić, jeść oder kupować steht im Akkusativ. Feminine Nomen auf -a enden dann auf -ę.",
    pattern:"kawa → kawę · woda → wodę · zupa → zupę · ryba → rybę"},
  acc_mn:{name:"Akkusativ = Grundform (unbelebt m, n)",stage:2,
    why:"Bei unbelebten maskulinen und bei neutralen Nomen ist der Akkusativ gleich der Grundform. Nur belebte maskuline Nomen, also Personen und Tiere, bekommen -a.",
    pattern:"chleb → chleb · ser → ser · mleko → mleko · masło → masło"},
  acc_fcons:{name:"Akkusativ feminin auf Konsonant",stage:2,
    why:"Feminine Nomen, die auf einen Konsonanten enden, bleiben im Akkusativ unverändert.",
    pattern:"sól → sól · noc → noc · rzecz → rzecz"},
  gen_neg:{name:"Genitiv nach Verneinung",stage:3,
    why:"Verlangt ein Verb sonst den Akkusativ, steht das Objekt nach nie im Genitiv. Feminin -a → -y bzw. -i nach k, g, l und weichen Lauten; maskulin meist -a, manchmal -u; neutral -o → -a.",
    pattern:"Mam kawę. → Nie mam kawy. · Jem chleb. → Nie jem chleba. · Kupuję cukier. → Nie kupuję cukru."},
  gen_qty:{name:"Genitiv nach Mengen",stage:3,
    why:"Nach Mengenangaben wie szklanka, kawałek, łyżka, kilogram oder trochę steht das Nomen im Genitiv. Die Endungen sind dieselben wie nach der Verneinung.",
    pattern:"szklanka wody · kawałek sera · łyżka mąki · trochę soli · kilogram cebuli"},
  aspect:{name:"Verbaspekt",stage:4,
    why:"Imperfektive Verben (gotować) beschreiben einen Vorgang, etwas Wiederholtes oder eine Gewohnheit. Perfektive Verben (ugotować) betonen das abgeschlossene Ergebnis. Im Präsens gebildet bedeuten perfektive Verben Zukunft: ugotuję heißt „ich werde fertig kochen“.",
    pattern:"Codziennie gotuję. (Gewohnheit) · Jutro ugotuję zupę. (Ergebnis, Zukunft)"},
  past_1:{name:"Vergangenheit ich/du: -łem, -łam, -łeś, -łaś",stage:5,
    why:"Vom Infinitiv fällt -ć weg, dann kommen -ł- und eine Personalendung. Die Endung zeigt das Geschlecht der Person: Ein Mann sagt -łem, eine Frau -łam. Bei du entsprechend -łeś und -łaś.",
    pattern:"robić → robiłem / robiłam · zrobić → zrobiłeś / zrobiłaś · nalać → nalałem / nalałam"},
  past_3:{name:"Vergangenheit er/sie: -ł, -ła",stage:5,
    why:"Bei er, sie und es gibt es keine Personalendung. Es bleibt nur -ł (er), -ła (sie) oder -ło (es).",
    pattern:"pić → pił, piła · kupić → kupił, kupiła · być → był, była, było"},
  past_pl:{name:"Vergangenheit Plural: -li, -ły",stage:5,
    why:"Im Plural zählt nur, ob ein Mann dabei ist: Dann endet die Form auf -li, sonst auf -ły. Für wir kommt -śmy dazu, für ihr -ście.",
    pattern:"czekać → czekali / czekały · zrobić → zrobiliśmy / zrobiłyśmy"},
  past_irr:{name:"Unregelmäßige Vergangenheit",stage:5,
    why:"Einige häufige Verben ändern in der Vergangenheit ihren Stamm. Diese Formen muss man lernen.",
    pattern:"jeść → jadłem, jadła, jedli · zjeść → zjedliśmy · wziąć → wziąłem, wzięła"},
  instr_mn:{name:"Instrumental maskulin/neutral: -em",stage:6,
    why:"Maskuline und neutrale Nomen enden im Instrumental auf -em, nach k und g auf -iem. Er steht nach z (mit) und für das Werkzeug, mit dem man etwas tut.",
    pattern:"nóż → nożem · mleko → mlekiem · mikser → mikserem · ser → serem"},
  instr_f:{name:"Instrumental feminin: -ą",stage:6,
    why:"Feminine Nomen enden im Instrumental auf -ą.",
    pattern:"łyżka → łyżką · cytryna → cytryną · szynka → szynką · kapusta → kapustą"},
  instr_byc:{name:"być + Instrumental",stage:6,
    why:"Sagt man mit być, was oder wer jemand ist, steht das Nomen im Instrumental.",
    pattern:"Jestem projektantem. · Brat jest kucharzem. · Ona jest lekarką."},
  loc_f:{name:"Lokativ feminin",stage:7,
    why:"Nach w (in) und na (auf) steht auf die Frage „Wo?“ der Lokativ. Feminine Nomen auf -ka werden zu -ce, auf -nia zu -ni. Bei anderen wird -a zu -e, und der Konsonant davor wird weich.",
    pattern:"lodówka → w lodówce · półka → na półce · patelnia → na patelni · kuchnia → w kuchni · woda → w wodzie"},
  loc_mn:{name:"Lokativ maskulin/neutral: -e oder -u",stage:7,
    why:"Maskuline und neutrale Nomen enden meist auf -e, und der Konsonant davor wird weich. Nach k, g und ch sowie nach weichen Lauten steht -u.",
    pattern:"stół → na stole · zlew → w zlewie · obiad → o obiedzie · garnek → w garnku · śniadanie → o śniadaniu"},
  dat_m:{name:"Dativ maskulin: -owi",stage:8,
    why:"Maskuline Nomen enden im Dativ meist auf -owi. Einige kurze, häufige Wörter haben -u.",
    pattern:"gość → gościowi · kelner → kelnerowi · brat → bratu · ojciec → ojcu"},
  dat_f:{name:"Dativ feminin: wie der Lokativ",stage:8,
    why:"Feminine Nomen haben im Dativ dieselbe Form wie im Lokativ.",
    pattern:"mama → mamie · siostra → siostrze · córka → córce"},
  dat_n:{name:"Dativ neutral: -u",stage:8,
    why:"Neutrale Nomen enden im Dativ auf -u.",
    pattern:"dziecko → dziecku · okno → oknu"},
  dat_pron:{name:"Dativ der Pronomen",stage:8,
    why:"Die kurzen Dativformen der Pronomen sind im Alltag sehr häufig, z. B. in Podaj mi … (Gib mir …) und Smakuje ci? (Schmeckt es dir?).",
    pattern:"ja → mi · ty → ci · on → mu · ona → jej · my → nam · oni → im"},
  fut_pf:{name:"Zukunft perfektiv: die Präsensform",stage:9,
    why:"Perfektive Verben haben keine Gegenwart. Ihre Präsensform bedeutet Zukunft mit Ergebnis: ugotuję = ich werde fertig kochen.",
    pattern:"ugotować → ugotuję · zrobić → zrobi · zamówić → zamówimy · otworzyć → otworzę"},
  fut_byc:{name:"Zukunft mit będę",stage:9,
    why:"być bildet die Zukunft mit będę, będziesz, będzie, będziemy, będziecie, będą. Mit einem imperfektiven Infinitiv entsteht die Zukunft für Vorgänge.",
    pattern:"będę gotować · będziesz jeść · będą czekać"},
  num_234:{name:"2, 3, 4: Nominativ Plural",stage:10,
    why:"Nach dwa, trzy und cztery steht der Nominativ Plural. Bei femininen Nomen heißt zwei dwie.",
    pattern:"dwa jabłka · trzy cytryny · dwie gruszki · cztery pomidory"},
  gen_pl_fn:{name:"Genitiv Plural feminin/neutral: ohne Endung",stage:10,
    why:"Ab fünf und nach dużo, mało, kilka oder ile steht der Genitiv Plural. Feminine und neutrale Nomen verlieren dabei ihre Endung, oft schiebt sich ein -e- ein.",
    pattern:"jabłko → pięć jabłek · truskawka → dużo truskawek · jajko → sześć jajek · papryka → ile papryk"},
  gen_pl_m:{name:"Genitiv Plural maskulin: -ów",stage:10,
    why:"Maskuline Nomen enden im Genitiv Plural meist auf -ów.",
    pattern:"pomidor → pomidorów · ogórek → ogórków · grzyb → grzybów · ziemniak → ziemniaków"}
};

/* Einstiegstest: 3 Fragen pro Stufe 1–7. Die erste Option ist richtig. */
KROK.test = [
  {s:1,q:"Ja ___ kawę.",h:"pić",o:["piję","pije","pijesz","pijemy"]},
  {s:1,q:"Ty ___ dużo.",h:"robić",o:["robisz","robi","robię","robimy"]},
  {s:1,q:"Oni ___ obiad.",h:"jeść",o:["jedzą","jemy","je","jecie"]},
  {s:2,q:"Lubię ___.",h:"herbata",o:["herbatę","herbata","herbaty","herbacie"]},
  {s:2,q:"Kupuję ___.",h:"ser",o:["ser","sera","serem","serze"]},
  {s:2,q:"Widzę ___.",h:"mama",o:["mamę","mama","mamy","mamą"]},
  {s:3,q:"Nie mam ___.",h:"czas",o:["czasu","czas","czasem","czasie"]},
  {s:3,q:"Nie lubię ___.",h:"kawa",o:["kawy","kawę","kawa","kawą"]},
  {s:3,q:"Szklanka ___.",h:"mleko",o:["mleka","mleko","mlekiem","mleku"]},
  {s:4,q:"Codziennie ___ gazetę.",h:"Jeden Tag lese ich die Zeitung.",o:["czytam","przeczytam"]},
  {s:4,q:"Kiedy ___ list, wyślę go.",h:"Wenn ich den Brief fertig geschrieben habe, schicke ich ihn ab.",o:["napiszę","piszę"]},
  {s:4,q:"Właśnie ___ obiad, nie mogę rozmawiać.",h:"Ich mache gerade Mittagessen.",o:["robię","zrobię"]},
  {s:5,q:"Wczoraj ___ w domu.",h:"być · ich (männlich)",o:["byłem","byłam","był","była"]},
  {s:5,q:"Ona ___ książkę.",h:"czytać · Vergangenheit",o:["czytała","czytał","czytałam","czytali"]},
  {s:5,q:"My ___ do kina.",h:"pójść · wir (gemischt)",o:["poszliśmy","poszli","poszłyśmy","poszedłem"]},
  {s:6,q:"Jestem ___.",h:"projektant",o:["projektantem","projektanta","projektant","projektancie"]},
  {s:6,q:"Kawa z ___.",h:"mleko",o:["mlekiem","mleka","mleko","mleku"]},
  {s:6,q:"Jadę ___.",h:"tramwaj",o:["tramwajem","tramwaj","tramwaju","tramwajowi"]},
  {s:7,q:"Mieszkam w ___.",h:"Hamburg",o:["Hamburgu","Hamburg","Hamburgiem","Hamburga"]},
  {s:7,q:"Rozmawiamy o ___.",h:"praca",o:["pracy","pracę","praca","pracą"]},
  {s:7,q:"Jesteśmy w ___.",h:"kuchnia",o:["kuchni","kuchnię","kuchnia","kuchnią"]}
];

/* Themen-Kapitel in Lernreihenfolge */
KROK.chapterNames = ["Küche & Essen","Zuhause","Einkaufen","Unterwegs & Reisen","Arbeit","Familie & Leute","Körper & Gesundheit","Freizeit & Sport","Zeit & Wetter","Gefühle & Meinungen"];
