/* Kapitel 1: Küche & Essen.
   Nomen: g = Genus (m/f/n). Verben: impf/pf = Aspektpaar, ja/ty = Präsens 1./2. Person Singular, rule = Konjugationsregel.
   Aufgaben: q = Satz mit ___, base = Grundform (+ Person), a = Lösung, de = Übersetzung, rule = Regel, mc = Auswahl statt Tippen.
   m = erwartete Grammatik für das Prüfskript: "Lemma|Merkmal=Wert|…" (Merkmale wie in Universal Dependencies). */
KROK.chapters.push({
  id: "kueche",
  name: "Küche & Essen",
  levels: {
    1: { note: "Präsens · Akkusativ", stage: 2 },
    2: { note: "+ Genitiv nach Verneinung", stage: 3 },
    3: { note: "+ Mengen · Verbaspekt", stage: 4 },
    4: { note: "Frühstück · Vergangenheit", stage: 5 },
    5: { note: "Zubereiten · Instrumental", stage: 6 },
    6: { note: "Aufbewahren · Lokativ", stage: 7 },
    7: { note: "Am Tisch · Dativ", stage: 8 },
    8: { note: "Pläne · Zukunft", stage: 9 },
    9: { note: "Einkaufen · Zahlen", stage: 10 },
    10: { note: "Gäste · alles gemischt", stage: 10 }
  },
  nouns: [
  // Level 1
  {id:"kawa",pl:"kawa",de:"Kaffee",g:"f",lvl:1},
  {id:"herbata",pl:"herbata",de:"Tee",g:"f",lvl:1},
  {id:"woda",pl:"woda",de:"Wasser",g:"f",lvl:1},
  {id:"chleb",pl:"chleb",de:"Brot",g:"m",lvl:1},
  {id:"mleko",pl:"mleko",de:"Milch",g:"n",lvl:1},
  {id:"ser",pl:"ser",de:"Käse",g:"m",lvl:1},
  {id:"jajko",pl:"jajko",de:"Ei",g:"n",lvl:1},
  {id:"zupa",pl:"zupa",de:"Suppe",g:"f",lvl:1},
  // Level 2
  {id:"jablko",pl:"jabłko",de:"Apfel",g:"n",lvl:2},
  {id:"maslo",pl:"masło",de:"Butter",g:"n",lvl:2},
  {id:"mieso",pl:"mięso",de:"Fleisch",g:"n",lvl:2},
  {id:"ryba",pl:"ryba",de:"Fisch",g:"f",lvl:2},
  {id:"sol",pl:"sól",de:"Salz",g:"f",lvl:2},
  {id:"cukier",pl:"cukier",de:"Zucker",g:"m",lvl:2},
  {id:"garnek",pl:"garnek",de:"Topf",g:"m",lvl:2},
  {id:"noz",pl:"nóż",de:"Messer",g:"m",lvl:2},
  // Level 3
  {id:"talerz",pl:"talerz",de:"Teller",g:"m",lvl:3},
  {id:"lyzka",pl:"łyżka",de:"Löffel",g:"f",lvl:3},
  {id:"widelec",pl:"widelec",de:"Gabel",g:"m",lvl:3},
  {id:"szklanka",pl:"szklanka",de:"Glas (Trinkglas)",g:"f",lvl:3},
  {id:"maka",pl:"mąka",de:"Mehl",g:"f",lvl:3},
  {id:"pomidor",pl:"pomidor",de:"Tomate",g:"m",lvl:3},
  {id:"cebula",pl:"cebula",de:"Zwiebel",g:"f",lvl:3},
  {id:"kuchnia",pl:"kuchnia",de:"Küche",g:"f",lvl:3},
  // Level 4
  {id:"bulka",pl:"bułka",de:"Brötchen",g:"f",lvl:4},
  {id:"jogurt",pl:"jogurt",de:"Joghurt",g:"m",lvl:4},
  {id:"sok",pl:"sok",de:"Saft",g:"m",lvl:4},
  {id:"dzem",pl:"dżem",de:"Marmelade",g:"m",lvl:4},
  {id:"miod",pl:"miód",de:"Honig",g:"m",lvl:4},
  {id:"szynka",pl:"szynka",de:"Schinken",g:"f",lvl:4},
  {id:"kielbasa",pl:"kiełbasa",de:"Wurst",g:"f",lvl:4},
  {id:"banan",pl:"banan",de:"Banane",g:"m",lvl:4},
  // Level 5
  {id:"patelnia",pl:"patelnia",de:"Pfanne",g:"f",lvl:5},
  {id:"deska",pl:"deska",de:"Schneidebrett",g:"f",lvl:5},
  {id:"lyzeczka",pl:"łyżeczka",de:"Teelöffel",g:"f",lvl:5},
  {id:"czajnik",pl:"czajnik",de:"Wasserkocher",g:"m",lvl:5},
  {id:"mikser",pl:"mikser",de:"Mixer",g:"m",lvl:5},
  {id:"piekarnik",pl:"piekarnik",de:"Backofen",g:"m",lvl:5},
  {id:"kuchenka",pl:"kuchenka",de:"Herd",g:"f",lvl:5},
  {id:"olej",pl:"olej",de:"Öl",g:"m",lvl:5},
  // Level 6
  {id:"lodowka",pl:"lodówka",de:"Kühlschrank",g:"f",lvl:6},
  {id:"szafka",pl:"szafka",de:"Schrank",g:"f",lvl:6},
  {id:"stol",pl:"stół",de:"Tisch",g:"m",lvl:6},
  {id:"zlew",pl:"zlew",de:"Spüle",g:"m",lvl:6},
  {id:"polka",pl:"półka",de:"Regal",g:"f",lvl:6},
  {id:"butelka",pl:"butelka",de:"Flasche",g:"f",lvl:6},
  {id:"sloik",pl:"słoik",de:"Einmachglas",g:"m",lvl:6},
  {id:"kubek",pl:"kubek",de:"Becher",g:"m",lvl:6},
  // Level 7
  {id:"gosc",pl:"gość",de:"Gast",g:"m",lvl:7},
  {id:"kelner",pl:"kelner",de:"Kellner",g:"m",lvl:7},
  {id:"rachunek",pl:"rachunek",de:"Rechnung",g:"m",lvl:7},
  {id:"serwetka",pl:"serwetka",de:"Serviette",g:"f",lvl:7},
  {id:"filizanka",pl:"filiżanka",de:"Tasse",g:"f",lvl:7},
  {id:"miska",pl:"miska",de:"Schüssel",g:"f",lvl:7},
  {id:"deser",pl:"deser",de:"Nachtisch",g:"m",lvl:7},
  {id:"kolacja",pl:"kolacja",de:"Abendessen",g:"f",lvl:7},
  // Level 8
  {id:"przepis",pl:"przepis",de:"Rezept",g:"m",lvl:8},
  {id:"ciasto",pl:"ciasto",de:"Kuchen",g:"n",lvl:8},
  {id:"salatka",pl:"sałatka",de:"Salat",g:"f",lvl:8},
  {id:"ryz",pl:"ryż",de:"Reis",g:"m",lvl:8},
  {id:"makaron",pl:"makaron",de:"Nudeln",g:"m",lvl:8},
  {id:"kurczak",pl:"kurczak",de:"Hähnchen",g:"m",lvl:8},
  {id:"ziemniak",pl:"ziemniak",de:"Kartoffel",g:"m",lvl:8},
  {id:"marchewka",pl:"marchewka",de:"Karotte",g:"f",lvl:8},
  // Level 9
  {id:"truskawka",pl:"truskawka",de:"Erdbeere",g:"f",lvl:9},
  {id:"cytryna",pl:"cytryna",de:"Zitrone",g:"f",lvl:9},
  {id:"ogorek",pl:"ogórek",de:"Gurke",g:"m",lvl:9},
  {id:"papryka",pl:"papryka",de:"Paprika",g:"f",lvl:9},
  {id:"czosnek",pl:"czosnek",de:"Knoblauch",g:"m",lvl:9},
  {id:"grzyb",pl:"grzyb",de:"Pilz",g:"m",lvl:9},
  {id:"sliwka",pl:"śliwka",de:"Pflaume",g:"f",lvl:9},
  {id:"gruszka",pl:"gruszka",de:"Birne",g:"f",lvl:9},
  // Level 10
  {id:"kucharz",pl:"kucharz",de:"Koch",g:"m",lvl:10},
  {id:"kanapka",pl:"kanapka",de:"belegtes Brot",g:"f",lvl:10},
  {id:"sniadanie",pl:"śniadanie",de:"Frühstück",g:"n",lvl:10},
  {id:"obiad",pl:"obiad",de:"Mittagessen",g:"m",lvl:10},
  {id:"pieprz",pl:"pieprz",de:"Pfeffer",g:"m",lvl:10},
  {id:"smietana",pl:"śmietana",de:"saure Sahne",g:"f",lvl:10},
  {id:"kapusta",pl:"kapusta",de:"Kohl",g:"f",lvl:10},
  {id:"wino",pl:"wino",de:"Wein",g:"n",lvl:10}
],
  verbs: [
  {id:"pic",impf:"pić",pf:"wypić",de:"trinken",ja:"piję",ty:"pijesz",rule:"praes_e",lvl:1},
  {id:"jesc",impf:"jeść",pf:"zjeść",de:"essen",ja:"jem",ty:"jesz",rule:"jesc",lvl:1},
  {id:"robic",impf:"robić",pf:"zrobić",de:"machen",ja:"robię",ty:"robisz",rule:"praes_i",lvl:1},
  {id:"gotowac",impf:"gotować",pf:"ugotować",de:"kochen",ja:"gotuję",ty:"gotujesz",rule:"praes_e",lvl:1},
  {id:"kupowac",impf:"kupować",pf:"kupić",de:"kaufen",ja:"kupuję",ty:"kupujesz",rule:"praes_e",lvl:2},
  {id:"kroic",impf:"kroić",pf:"pokroić",de:"schneiden",ja:"kroję",ty:"kroisz",rule:"praes_i",lvl:2},
  {id:"myc",impf:"myć",pf:"umyć",de:"waschen, spülen",ja:"myję",ty:"myjesz",rule:"praes_e",lvl:2},
  {id:"dodawac",impf:"dodawać",pf:"dodać",de:"hinzufügen",ja:"dodaję",ty:"dodajesz",rule:"praes_e",lvl:2},
  {id:"smazyc",impf:"smażyć",pf:"usmażyć",de:"braten",ja:"smażę",ty:"smażysz",rule:"praes_i",lvl:3},
  {id:"piec",impf:"piec",pf:"upiec",de:"backen",ja:"piekę",ty:"pieczesz",rule:"praes_e",lvl:3},
  {id:"mieszac",impf:"mieszać",pf:"wymieszać",de:"umrühren",ja:"mieszam",ty:"mieszasz",rule:"praes_am",lvl:3},
  {id:"nakrywac",impf:"nakrywać",pf:"nakryć",de:"(den Tisch) decken",ja:"nakrywam",ty:"nakrywasz",rule:"praes_am",lvl:3},
  {id:"brac",impf:"brać",pf:"wziąć",de:"nehmen",ja:"biorę",ty:"bierzesz",rule:"praes_e",lvl:4},
  {id:"probowac",impf:"próbować",pf:"spróbować",de:"probieren",ja:"próbuję",ty:"próbujesz",rule:"praes_e",lvl:4},
  {id:"nalewac",impf:"nalewać",pf:"nalać",de:"eingießen",ja:"nalewam",ty:"nalewasz",rule:"praes_am",lvl:4},
  {id:"czekac",impf:"czekać",pf:"poczekać",de:"warten",ja:"czekam",ty:"czekasz",rule:"praes_am",lvl:4},
  {id:"obierac",impf:"obierać",pf:"obrać",de:"schälen",ja:"obieram",ty:"obierasz",rule:"praes_am",lvl:5},
  {id:"przygotowywac",impf:"przygotowywać",pf:"przygotować",de:"zubereiten",ja:"przygotowuję",ty:"przygotowujesz",rule:"praes_e",lvl:5},
  {id:"podgrzewac",impf:"podgrzewać",pf:"podgrzać",de:"aufwärmen",ja:"podgrzewam",ty:"podgrzewasz",rule:"praes_am",lvl:5},
  {id:"solic",impf:"solić",pf:"posolić",de:"salzen",ja:"solę",ty:"solisz",rule:"praes_i",lvl:5},
  {id:"wkladac",impf:"wkładać",pf:"włożyć",de:"hineinlegen",ja:"wkładam",ty:"wkładasz",rule:"praes_am",lvl:6},
  {id:"wyjmowac",impf:"wyjmować",pf:"wyjąć",de:"herausnehmen",ja:"wyjmuję",ty:"wyjmujesz",rule:"praes_e",lvl:6},
  {id:"stawiac",impf:"stawiać",pf:"postawić",de:"hinstellen",ja:"stawiam",ty:"stawiasz",rule:"praes_am",lvl:6},
  {id:"szukac",impf:"szukać",pf:"poszukać",de:"suchen",ja:"szukam",ty:"szukasz",rule:"praes_am",lvl:6},
  {id:"dawac",impf:"dawać",pf:"dać",de:"geben",ja:"daję",ty:"dajesz",rule:"praes_e",lvl:7},
  {id:"podawac",impf:"podawać",pf:"podać",de:"reichen, servieren",ja:"podaję",ty:"podajesz",rule:"praes_e",lvl:7},
  {id:"pomagac",impf:"pomagać",pf:"pomóc",de:"helfen",ja:"pomagam",ty:"pomagasz",rule:"praes_am",lvl:7},
  {id:"placic",impf:"płacić",pf:"zapłacić",de:"bezahlen",ja:"płacę",ty:"płacisz",rule:"praes_i",lvl:7},
  {id:"zamawiac",impf:"zamawiać",pf:"zamówić",de:"bestellen",ja:"zamawiam",ty:"zamawiasz",rule:"praes_am",lvl:8},
  {id:"zmywac",impf:"zmywać",pf:"zmyć",de:"abspülen",ja:"zmywam",ty:"zmywasz",rule:"praes_am",lvl:8},
  {id:"sprzatac",impf:"sprzątać",pf:"posprzątać",de:"aufräumen",ja:"sprzątam",ty:"sprzątasz",rule:"praes_am",lvl:8},
  {id:"klasc",impf:"kłaść",pf:"położyć",de:"legen",ja:"kładę",ty:"kładziesz",rule:"praes_e",lvl:8},
  {id:"wazyc",impf:"ważyć",pf:"zważyć",de:"wiegen",ja:"ważę",ty:"ważysz",rule:"praes_i",lvl:9},
  {id:"mrozic",impf:"mrozić",pf:"zamrozić",de:"einfrieren",ja:"mrożę",ty:"mrozisz",rule:"praes_i",lvl:9},
  {id:"dzielic",impf:"dzielić",pf:"podzielić",de:"teilen",ja:"dzielę",ty:"dzielisz",rule:"praes_i",lvl:9},
  {id:"zostawiac",impf:"zostawiać",pf:"zostawić",de:"übrig lassen",ja:"zostawiam",ty:"zostawiasz",rule:"praes_am",lvl:9},
  {id:"otwierac",impf:"otwierać",pf:"otworzyć",de:"öffnen",ja:"otwieram",ty:"otwierasz",rule:"praes_am",lvl:10},
  {id:"zamykac",impf:"zamykać",pf:"zamknąć",de:"schließen",ja:"zamykam",ty:"zamykasz",rule:"praes_am",lvl:10},
  {id:"slodzic",impf:"słodzić",pf:"posłodzić",de:"süßen",ja:"słodzę",ty:"słodzisz",rule:"praes_i",lvl:10},
  {id:"wylewac",impf:"wylewać",pf:"wylać",de:"ausgießen, weggießen",ja:"wylewam",ty:"wylewasz",rule:"praes_am",lvl:10}
],
  drills: [
  // Level 1: Präsens + Akkusativ
  {id:"d01",lvl:1,q:"Rano piję ___.",base:"kawa",a:"kawę",de:"Morgens trinke ich Kaffee.",rule:"acc_f",m:"kawa|Case=Acc|Number=Sing"},
  {id:"d02",lvl:1,q:"Ja ___ zupę.",base:"gotować · ja",a:"gotuję",de:"Ich koche Suppe.",rule:"praes_e",m:"gotować|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d03",lvl:1,q:"Codziennie jem ___.",base:"chleb",a:"chleb",de:"Jeden Tag esse ich Brot.",rule:"acc_mn",m:"chleb|Case=Acc|Number=Sing"},
  {id:"d04",lvl:1,q:"Ty ___ obiad?",base:"robić · ty",a:"robisz",de:"Machst du das Mittagessen?",rule:"praes_i",m:"robić|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d05",lvl:1,q:"Ona pije ___.",base:"woda",a:"wodę",de:"Sie trinkt Wasser.",rule:"acc_f",m:"woda|Case=Acc|Number=Sing"},
  {id:"d06",lvl:1,q:"My ___ ser.",base:"jeść · my",a:"jemy",de:"Wir essen Käse.",rule:"jesc",m:"jeść|Person=1|Number=Plur|Tense=Pres|VerbForm=Fin"},
  {id:"d07",lvl:1,q:"Czy ___ herbatę?",base:"pić · ty",a:"pijesz",de:"Trinkst du Tee?",rule:"praes_e",m:"pić|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d08",lvl:1,q:"On je ___ na śniadanie.",base:"jajko",a:"jajko",de:"Er isst ein Ei zum Frühstück.",rule:"acc_mn",m:"jajko|Case=Acc|Number=Sing"},
  {id:"d09",lvl:1,q:"Oni ___ kolację.",base:"jeść · oni",a:"jedzą",de:"Sie essen Abendbrot.",rule:"jesc",m:"jeść|Person=3|Number=Plur|Tense=Pres|VerbForm=Fin"},
  {id:"d10",lvl:1,q:"Gotujesz ___?",base:"zupa",a:"zupę",de:"Kochst du Suppe?",rule:"acc_f",m:"zupa|Case=Acc|Number=Sing"},
  // Level 2: + Genitiv nach Verneinung
  {id:"d11",lvl:2,q:"Kupuję ___ na obiad.",base:"ryba",a:"rybę",de:"Ich kaufe Fisch fürs Mittagessen.",rule:"acc_f",m:"ryba|Case=Acc|Number=Sing"},
  {id:"d12",lvl:2,q:"Ty ___ jabłko.",base:"kroić · ty",a:"kroisz",de:"Du schneidest den Apfel.",rule:"praes_i",m:"kroić|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d13",lvl:2,q:"Ja ___ garnek.",base:"myć · ja",a:"myję",de:"Ich spüle den Topf.",rule:"praes_e",m:"myć|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d14",lvl:2,q:"Dodaję ___ do zupy.",base:"sól",a:"sól",de:"Ich gebe Salz in die Suppe.",rule:"acc_fcons",m:"sól|Case=Acc|Number=Sing"},
  {id:"d15",lvl:2,q:"Ona ___ mięso.",base:"kupować · ona",a:"kupuje",de:"Sie kauft Fleisch.",rule:"praes_e",m:"kupować|Person=3|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d16",lvl:2,q:"Czy ___ cukier do herbaty?",base:"dodawać · ty",a:"dodajesz",de:"Gibst du Zucker in den Tee?",rule:"praes_e",m:"dodawać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d17",lvl:2,q:"Mam ___ do chleba.",base:"masło",a:"masło",de:"Ich habe Butter fürs Brot.",rule:"acc_mn",m:"masło|Case=Acc|Number=Sing"},
  {id:"d18",lvl:2,q:"Nie mam ___.",base:"kawa",a:"kawy",de:"Ich habe keinen Kaffee.",rule:"gen_neg",m:"kawa|Case=Gen|Number=Sing"},
  {id:"d19",lvl:2,q:"Nie piję ___.",base:"mleko",a:"mleka",de:"Ich trinke keine Milch.",rule:"gen_neg",m:"mleko|Case=Gen|Number=Sing"},
  {id:"d20",lvl:2,q:"Nie jem ___.",base:"mięso",a:"mięsa",de:"Ich esse kein Fleisch.",rule:"gen_neg",m:"mięso|Case=Gen|Number=Sing"},
  {id:"d21",lvl:2,q:"Nie mamy ___.",base:"chleb",a:"chleba",de:"Wir haben kein Brot.",rule:"gen_neg",m:"chleb|Case=Gen|Number=Sing"},
  {id:"d22",lvl:2,q:"Nie kupuję ___.",base:"cukier",a:"cukru",de:"Ich kaufe keinen Zucker.",rule:"gen_neg",m:"cukier|Case=Gen|Number=Sing",note:"cukier gehört zu den maskulinen Nomen mit -u im Genitiv, wie viele Stoffe: cukru, ryżu."},
  // Level 3: + Genitiv nach Mengen, Verbaspekt
  {id:"d23",lvl:3,q:"Szklanka ___, proszę.",base:"woda",a:"wody",de:"Ein Glas Wasser, bitte.",rule:"gen_qty",m:"woda|Case=Gen|Number=Sing"},
  {id:"d24",lvl:3,q:"Poproszę kawałek ___.",base:"ser",a:"sera",de:"Ich hätte gern ein Stück Käse.",rule:"gen_qty",m:"ser|Case=Gen|Number=Sing"},
  {id:"d25",lvl:3,q:"Dodaj łyżkę ___.",base:"mąka",a:"mąki",de:"Gib einen Löffel Mehl dazu.",rule:"gen_qty",m:"mąka|Case=Gen|Number=Sing",note:"Nach k steht -i statt -y: mąka → mąki."},
  {id:"d26",lvl:3,q:"Dodaj trochę ___.",base:"sól",a:"soli",de:"Gib etwas Salz dazu.",rule:"gen_qty",m:"sól|Case=Gen|Number=Sing"},
  {id:"d27",lvl:3,q:"Kupuję kilogram ___.",base:"cebula",a:"cebuli",de:"Ich kaufe ein Kilo Zwiebeln.",rule:"gen_qty",m:"cebula|Case=Gen|Number=Sing",note:"Nach l steht -i: cebula → cebuli."},
  {id:"d28",lvl:3,q:"Nie mam ___.",base:"widelec",a:"widelca",de:"Ich habe keine Gabel.",rule:"gen_neg",m:"widelec|Case=Gen|Number=Sing",note:"Das e in widelec fällt weg: widelec → widelca (bewegliches e)."},
  {id:"d29",lvl:3,q:"Ja ___ rybę.",base:"smażyć · ja",a:"smażę",de:"Ich brate den Fisch.",rule:"praes_i",m:"smażyć|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d30",lvl:3,q:"Ty ___ zupę?",base:"mieszać · ty",a:"mieszasz",de:"Rührst du die Suppe um?",rule:"praes_am",m:"mieszać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d31",lvl:3,q:"Dziś ja ___ do stołu.",base:"nakrywać · ja",a:"nakrywam",de:"Heute decke ich den Tisch.",rule:"praes_am",m:"nakrywać|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d32",lvl:3,q:"Codziennie rano ___ kawę.",mc:["piję","wypiję"],a:"piję",de:"Jeden Morgen trinke ich Kaffee.",rule:"aspect",m:"pić|Aspect=Imp|Person=1|Number=Sing",note:"Gewohnheit → imperfektiv."},
  {id:"d33",lvl:3,q:"Jutro ___ ciasto i przyniosę je do pracy.",mc:["piekę","upiekę"],a:"upiekę",de:"Morgen backe ich einen Kuchen und bringe ihn zur Arbeit mit.",rule:"aspect",m:"upiec|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin",note:"Fertiges Ergebnis in der Zukunft → perfektiv."},
  {id:"d34",lvl:3,q:"Poczekaj, właśnie ___ zupę.",mc:["gotuję","ugotuję"],a:"gotuję",de:"Warte, ich koche gerade Suppe.",rule:"aspect",m:"gotować|Aspect=Imp|Person=1|Number=Sing",note:"Vorgang, der gerade läuft → imperfektiv."},
  {id:"d35",lvl:3,q:"Za chwilę ___ jabłko i dam ci kawałek.",mc:["kroję","pokroję"],a:"pokroję",de:"Gleich schneide ich den Apfel auf und gebe dir ein Stück.",rule:"aspect",m:"pokroić|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin",note:"Einmalige, abgeschlossene Handlung → perfektiv."},
  // Level 4: Frühstück · Vergangenheit
  {id:"d36",lvl:4,q:"Wczoraj ___ bułkę z dżemem.",base:"jeść · ich (Mann)",a:"jadłem",de:"Gestern habe ich ein Brötchen mit Marmelade gegessen.",rule:"past_irr",m:"jeść|Tense=Past|Number=Sing|Gender=Masc|Person=1"},
  {id:"d37",lvl:4,q:"Ona ___ sok.",base:"pić · sie",a:"piła",de:"Sie hat Saft getrunken.",rule:"past_3",m:"pić|Tense=Past|Number=Sing|Gender=Fem"},
  {id:"d38",lvl:4,q:"Czy ___ już kawę?",base:"zrobić · du (Mann)",a:"zrobiłeś",de:"Hast du schon Kaffee gemacht?",rule:"past_1",m:"zrobić|Tense=Past|Number=Sing|Gender=Masc|Person=2"},
  {id:"d39",lvl:4,q:"Rano ___ herbatę.",base:"nalać · ich (Frau)",a:"nalałam",de:"Am Morgen habe ich Tee eingegossen.",rule:"past_1",m:"nalać|Tense=Past|Number=Sing|Gender=Fem|Person=1"},
  {id:"d40",lvl:4,q:"Oni długo ___ na śniadanie.",base:"czekać · sie (Männer)",a:"czekali",de:"Sie haben lange auf das Frühstück gewartet.",rule:"past_pl",m:"czekać|Tense=Past|Number=Plur"},
  {id:"d41",lvl:4,q:"Kto ___ ostatnią bułkę?",base:"wziąć · er",a:"wziął",de:"Wer hat das letzte Brötchen genommen?",rule:"past_irr",m:"wziąć|Tense=Past|Number=Sing|Gender=Masc"},
  {id:"d42",lvl:4,q:"Wczoraj ___ nowego jogurtu.",base:"spróbować · ich (Mann)",a:"spróbowałem",de:"Gestern habe ich einen neuen Joghurt probiert.",rule:"past_1",m:"spróbować|Tense=Past|Number=Sing|Gender=Masc|Person=1",note:"spróbować verlangt den Genitiv: nowego jogurtu."},
  {id:"d43",lvl:4,q:"Ona ___ szynkę i ser.",base:"kupić · sie",a:"kupiła",de:"Sie hat Schinken und Käse gekauft.",rule:"past_3",m:"kupić|Tense=Past|Number=Sing|Gender=Fem"},
  {id:"d44",lvl:4,q:"My ___ śniadanie o ósmej.",base:"zjeść · wir (gemischt)",a:"zjedliśmy",de:"Wir haben um acht gefrühstückt.",rule:"past_irr",m:"zjeść|Tense=Past|Number=Plur|Person=1"},
  {id:"d45",lvl:4,q:"Ja ___ bułkę.",base:"brać · ich",a:"biorę",de:"Ich nehme ein Brötchen.",rule:"praes_e",m:"brać|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d46",lvl:4,q:"Ty ___ sok?",base:"nalewać · du",a:"nalewasz",de:"Gießt du Saft ein?",rule:"praes_am",m:"nalewać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d47",lvl:4,q:"Wczoraj cały wieczór ___.",mc:["gotowałem", "ugotowałem"],a:"gotowałem",de:"Gestern habe ich den ganzen Abend gekocht.",rule:"aspect",m:"gotować|Aspect=Imp|Tense=Past|Number=Sing|Gender=Masc|Person=1",note:"Dauer, Vorgang → imperfektiv."},
  {id:"d48",lvl:4,q:"W końcu ___ zupę i zjedliśmy obiad.",mc:["gotowałem", "ugotowałem"],a:"ugotowałem",de:"Schließlich habe ich die Suppe fertig gekocht, und wir haben gegessen.",rule:"aspect",m:"ugotować|Aspect=Perf|Tense=Past|Number=Sing|Gender=Masc|Person=1",note:"Abgeschlossenes Ergebnis → perfektiv."},
  // Level 5: Zubereiten · Instrumental
  {id:"d49",lvl:5,q:"Kroję chleb ___.",base:"nóż",a:"nożem",de:"Ich schneide das Brot mit dem Messer.",rule:"instr_mn",m:"nóż|Case=Ins|Number=Sing"},
  {id:"d50",lvl:5,q:"Kawa z ___, proszę.",base:"mleko",a:"mlekiem",de:"Kaffee mit Milch, bitte.",rule:"instr_mn",m:"mleko|Case=Ins|Number=Sing"},
  {id:"d51",lvl:5,q:"Herbata z ___.",base:"cytryna",a:"cytryną",de:"Tee mit Zitrone.",rule:"instr_f",m:"cytryna|Case=Ins|Number=Sing"},
  {id:"d52",lvl:5,q:"Mieszam zupę ___.",base:"łyżka",a:"łyżką",de:"Ich rühre die Suppe mit dem Löffel um.",rule:"instr_f",m:"łyżka|Case=Ins|Number=Sing"},
  {id:"d53",lvl:5,q:"Chleb z ___.",base:"masło",a:"masłem",de:"Brot mit Butter.",rule:"instr_mn",m:"masło|Case=Ins|Number=Sing"},
  {id:"d54",lvl:5,q:"Kanapka z ___.",base:"szynka",a:"szynką",de:"Ein belegtes Brot mit Schinken.",rule:"instr_f",m:"szynka|Case=Ins|Number=Sing"},
  {id:"d55",lvl:5,q:"Mój brat jest ___.",base:"kucharz",a:"kucharzem",de:"Mein Bruder ist Koch.",rule:"instr_byc",m:"kucharz|Case=Ins|Number=Sing"},
  {id:"d56",lvl:5,q:"Makaron z ___.",base:"ser",a:"serem",de:"Nudeln mit Käse.",rule:"instr_mn",m:"ser|Case=Ins|Number=Sing"},
  {id:"d57",lvl:5,q:"Ubijam śmietanę ___.",base:"mikser",a:"mikserem",de:"Ich schlage die Sahne mit dem Mixer.",rule:"instr_mn",m:"mikser|Case=Ins|Number=Sing"},
  {id:"d58",lvl:5,q:"Ja ___ ziemniaki.",base:"obierać · ich",a:"obieram",de:"Ich schäle Kartoffeln.",rule:"praes_am",m:"obierać|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d59",lvl:5,q:"Co ___ na kolację?",base:"przygotowywać · du",a:"przygotowujesz",de:"Was bereitest du zum Abendessen zu?",rule:"praes_e",m:"przygotowywać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d60",lvl:5,q:"Ja ___ zupę.",base:"solić · ich",a:"solę",de:"Ich salze die Suppe.",rule:"praes_i",m:"solić|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d61",lvl:5,q:"On ___ obiad w piekarniku.",base:"podgrzewać · er",a:"podgrzewa",de:"Er wärmt das Mittagessen im Backofen auf.",rule:"praes_am",m:"podgrzewać|Person=3|Number=Sing|Tense=Pres|VerbForm=Fin"},
  // Level 6: Aufbewahren · Lokativ
  {id:"d62",lvl:6,q:"Mleko jest w ___.",base:"lodówka",a:"lodówce",de:"Die Milch ist im Kühlschrank.",rule:"loc_f",m:"lodówka|Case=Loc|Number=Sing"},
  {id:"d63",lvl:6,q:"Talerze są w ___.",base:"szafka",a:"szafce",de:"Die Teller sind im Schrank.",rule:"loc_f",m:"szafka|Case=Loc|Number=Sing"},
  {id:"d64",lvl:6,q:"Chleb leży na ___.",base:"stół",a:"stole",de:"Das Brot liegt auf dem Tisch.",rule:"loc_mn",m:"stół|Case=Loc|Number=Sing"},
  {id:"d65",lvl:6,q:"Naczynia są w ___.",base:"zlew",a:"zlewie",de:"Das Geschirr ist in der Spüle.",rule:"loc_mn",m:"zlew|Case=Loc|Number=Sing"},
  {id:"d66",lvl:6,q:"Cukier stoi na ___.",base:"półka",a:"półce",de:"Der Zucker steht auf dem Regal.",rule:"loc_f",m:"półka|Case=Loc|Number=Sing"},
  {id:"d67",lvl:6,q:"Zupa jest w ___.",base:"garnek",a:"garnku",de:"Die Suppe ist im Topf.",rule:"loc_mn",m:"garnek|Case=Loc|Number=Sing"},
  {id:"d68",lvl:6,q:"Woda jest w ___.",base:"butelka",a:"butelce",de:"Das Wasser ist in der Flasche.",rule:"loc_f",m:"butelka|Case=Loc|Number=Sing"},
  {id:"d69",lvl:6,q:"Rozmawiamy o ___.",base:"obiad",a:"obiedzie",de:"Wir reden über das Mittagessen.",rule:"loc_mn",m:"obiad|Case=Loc|Number=Sing",note:"Hier wechselt auch der Vokal: a → e, d → dzi."},
  {id:"d70",lvl:6,q:"Smażę jajko na ___.",base:"patelnia",a:"patelni",de:"Ich brate das Ei in der Pfanne.",rule:"loc_f",m:"patelnia|Case=Loc|Number=Sing"},
  {id:"d71",lvl:6,q:"Dżem jest w ___.",base:"słoik",a:"słoiku",de:"Die Marmelade ist im Glas.",rule:"loc_mn",m:"słoik|Case=Loc|Number=Sing"},
  {id:"d72",lvl:6,q:"Ja ___ mleko do lodówki.",base:"wkładać · ich",a:"wkładam",de:"Ich stelle die Milch in den Kühlschrank.",rule:"praes_am",m:"wkładać|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d73",lvl:6,q:"Ty ___ talerze z szafki?",base:"wyjmować · du",a:"wyjmujesz",de:"Nimmst du die Teller aus dem Schrank?",rule:"praes_e",m:"wyjmować|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d74",lvl:6,q:"Czego ___?",base:"szukać · du",a:"szukasz",de:"Was suchst du?",rule:"praes_am",m:"szukać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin",note:"szukać verlangt den Genitiv: czego?"},
  // Level 7: Am Tisch · Dativ
  {id:"d75",lvl:7,q:"Podaj ___ sól, proszę.",base:"ich",a:"mi",de:"Gib mir bitte das Salz.",rule:"dat_pron",m:"ja|Case=Dat"},
  {id:"d76",lvl:7,q:"Daję ___ kawę.",base:"mama",a:"mamie",de:"Ich gebe Mama Kaffee.",rule:"dat_f",m:"mama|Case=Dat|Number=Sing"},
  {id:"d77",lvl:7,q:"Pomagam ___ w kuchni.",base:"brat",a:"bratu",de:"Ich helfe dem Bruder in der Küche.",rule:"dat_m",m:"brat|Case=Dat|Number=Sing",note:"brat gehört zu den kurzen Wörtern mit -u statt -owi."},
  {id:"d78",lvl:7,q:"Kelner podaje ___ menu.",base:"gość",a:"gościowi",de:"Der Kellner reicht dem Gast die Speisekarte.",rule:"dat_m",m:"gość|Case=Dat|Number=Sing"},
  {id:"d79",lvl:7,q:"Daję ___ jabłko.",base:"dziecko",a:"dziecku",de:"Ich gebe dem Kind einen Apfel.",rule:"dat_n",m:"dziecko|Case=Dat|Number=Sing"},
  {id:"d80",lvl:7,q:"Pomagasz ___?",base:"siostra",a:"siostrze",de:"Hilfst du der Schwester?",rule:"dat_f",m:"siostra|Case=Dat|Number=Sing"},
  {id:"d81",lvl:7,q:"Dziękuję ___ za obiad.",base:"kelner",a:"kelnerowi",de:"Ich danke dem Kellner für das Essen.",rule:"dat_m",m:"kelner|Case=Dat|Number=Sing"},
  {id:"d82",lvl:7,q:"Smakuje ___ zupa?",base:"du",a:"ci",de:"Schmeckt dir die Suppe?",rule:"dat_pron",m:"ty|Case=Dat"},
  {id:"d83",lvl:7,q:"Podaj ___ chleb.",base:"er",a:"mu",de:"Gib ihm das Brot.",rule:"dat_pron",m:"on|Case=Dat"},
  {id:"d84",lvl:7,q:"Ja ___ rachunek.",base:"płacić · ich",a:"płacę",de:"Ich bezahle die Rechnung.",rule:"praes_i",m:"płacić|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d85",lvl:7,q:"Kelner ___ deser.",base:"podawać · er",a:"podaje",de:"Der Kellner serviert den Nachtisch.",rule:"praes_e",m:"podawać|Person=3|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d86",lvl:7,q:"My ___ mamie.",base:"pomagać · wir",a:"pomagamy",de:"Wir helfen Mama.",rule:"praes_am",m:"pomagać|Person=1|Number=Plur|Tense=Pres|VerbForm=Fin"},
  // Level 8: Pläne · Zukunft
  {id:"d87",lvl:8,q:"Jutro ___ obiad.",base:"ugotować · ich",a:"ugotuję",de:"Morgen koche ich das Mittagessen.",rule:"fut_pf",m:"ugotować|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin"},
  {id:"d88",lvl:8,q:"Wieczorem ___ naczynia.",base:"zmyć · ich",a:"zmyję",de:"Am Abend spüle ich das Geschirr ab.",rule:"fut_pf",m:"zmyć|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin"},
  {id:"d89",lvl:8,q:"Jutro ___ pizzę.",base:"zamówić · wir",a:"zamówimy",de:"Morgen bestellen wir Pizza.",rule:"fut_pf",m:"zamówić|Aspect=Perf|Person=1|Number=Plur|Tense=Fut|VerbForm=Fin"},
  {id:"d90",lvl:8,q:"Ona ___ sałatkę.",base:"zrobić · sie",a:"zrobi",de:"Sie wird den Salat machen.",rule:"fut_pf",m:"zrobić|Aspect=Perf|Person=3|Number=Sing|Tense=Fut|VerbForm=Fin"},
  {id:"d91",lvl:8,q:"Kiedy ___ kuchnię?",base:"posprzątać · du",a:"posprzątasz",de:"Wann räumst du die Küche auf?",rule:"fut_pf",m:"posprzątać|Aspect=Perf|Person=2|Number=Sing|Tense=Fut|VerbForm=Fin"},
  {id:"d92",lvl:8,q:"Jutro ___ gotować cały dzień.",base:"być · ich",a:"będę",de:"Morgen werde ich den ganzen Tag kochen.",rule:"fut_byc",m:"być|Tense=Fut|Person=1|Number=Sing"},
  {id:"d93",lvl:8,q:"Czy ___ jeść z nami?",base:"być · du",a:"będziesz",de:"Wirst du mit uns essen?",rule:"fut_byc",m:"być|Tense=Fut|Person=2|Number=Sing"},
  {id:"d94",lvl:8,q:"Oni ___ na nas czekać.",base:"być · sie",a:"będą",de:"Sie werden auf uns warten.",rule:"fut_byc",m:"być|Tense=Fut|Person=3|Number=Plur"},
  {id:"d95",lvl:8,q:"W weekend ___ dużo.",mc:["będę gotować", "ugotuję"],a:"będę gotować",de:"Am Wochenende werde ich viel kochen.",rule:"aspect",note:"Vorgang ohne bestimmtes Ergebnis → imperfektiv mit będę."},
  {id:"d96",lvl:8,q:"Jutro ___ zupę i zaniosę ją mamie.",mc:["ugotuję", "będę gotować"],a:"ugotuję",de:"Morgen koche ich die Suppe und bringe sie Mama.",rule:"aspect",m:"ugotować|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin",note:"Fertiges Ergebnis → perfektiv."},
  {id:"d97",lvl:8,q:"Ja ___ talerz na stół.",base:"kłaść · ich",a:"kładę",de:"Ich lege den Teller auf den Tisch.",rule:"praes_e",m:"kłaść|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d98",lvl:8,q:"Ty ___ naczynia?",base:"zmywać · du",a:"zmywasz",de:"Spülst du das Geschirr?",rule:"praes_am",m:"zmywać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  // Level 9: Einkaufen · Zahlen
  {id:"d99",lvl:9,q:"Kupuję pięć ___.",base:"jabłko",a:"jabłek",de:"Ich kaufe fünf Äpfel.",rule:"gen_pl_fn",m:"jabłko|Case=Gen|Number=Plur"},
  {id:"d100",lvl:9,q:"Mam dwa ___.",base:"jabłko",a:"jabłka",de:"Ich habe zwei Äpfel.",rule:"num_234",m:"jabłko|Case=Nom|Number=Plur"},
  {id:"d101",lvl:9,q:"Potrzebuję kilogram ___.",base:"pomidor",a:"pomidorów",de:"Ich brauche ein Kilo Tomaten.",rule:"gen_pl_m",m:"pomidor|Case=Gen|Number=Plur"},
  {id:"d102",lvl:9,q:"W lodówce jest sześć ___.",base:"jajko",a:"jajek",de:"Im Kühlschrank sind sechs Eier.",rule:"gen_pl_fn",m:"jajko|Case=Gen|Number=Plur"},
  {id:"d103",lvl:9,q:"Kupuję trzy ___.",base:"cytryna",a:"cytryny",de:"Ich kaufe drei Zitronen.",rule:"num_234",m:"cytryna|Case=Nom|Number=Plur"},
  {id:"d104",lvl:9,q:"Mamy dużo ___.",base:"truskawka",a:"truskawek",de:"Wir haben viele Erdbeeren.",rule:"gen_pl_fn",m:"truskawka|Case=Gen|Number=Plur"},
  {id:"d105",lvl:9,q:"Kupuję kilka ___.",base:"ogórek",a:"ogórków",de:"Ich kaufe ein paar Gurken.",rule:"gen_pl_m",m:"ogórek|Case=Gen|Number=Plur"},
  {id:"d106",lvl:9,q:"Obieram pięć ___.",base:"ziemniak",a:"ziemniaków",de:"Ich schäle fünf Kartoffeln.",rule:"gen_pl_m",m:"ziemniak|Case=Gen|Number=Plur"},
  {id:"d107",lvl:9,q:"W lesie jest dużo ___.",base:"grzyb",a:"grzybów",de:"Im Wald gibt es viele Pilze.",rule:"gen_pl_m",m:"grzyb|Case=Gen|Number=Plur"},
  {id:"d108",lvl:9,q:"Mam dwie ___.",base:"gruszka",a:"gruszki",de:"Ich habe zwei Birnen.",rule:"num_234",m:"gruszka|Case=Nom|Number=Plur",note:"Bei femininen Nomen heißt zwei dwie."},
  {id:"d109",lvl:9,q:"Zostało siedem ___.",base:"śliwka",a:"śliwek",de:"Es sind sieben Pflaumen übrig.",rule:"gen_pl_fn",m:"śliwka|Case=Gen|Number=Plur"},
  {id:"d110",lvl:9,q:"Ile ___ kupujesz?",base:"papryka",a:"papryk",de:"Wie viele Paprika kaufst du?",rule:"gen_pl_fn",m:"papryka|Case=Gen|Number=Plur"},
  {id:"d111",lvl:9,q:"Ja ___ mąkę.",base:"ważyć · ich",a:"ważę",de:"Ich wiege das Mehl ab.",rule:"praes_i",m:"ważyć|Person=1|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d112",lvl:9,q:"Ty ___ mięso?",base:"mrozić · du",a:"mrozisz",de:"Frierst du das Fleisch ein?",rule:"praes_i",m:"mrozić|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  // Level 10: Gäste · alles gemischt
  {id:"d113",lvl:10,q:"Nie ma ___ w lodówce.",base:"śmietana",a:"śmietany",de:"Es ist keine Sahne im Kühlschrank.",rule:"gen_neg",m:"śmietana|Case=Gen|Number=Sing"},
  {id:"d114",lvl:10,q:"Pierogi z ___.",base:"kapusta",a:"kapustą",de:"Piroggen mit Kohl.",rule:"instr_f",m:"kapusta|Case=Ins|Number=Sing"},
  {id:"d115",lvl:10,q:"Wino stoi w ___.",base:"kuchnia",a:"kuchni",de:"Der Wein steht in der Küche.",rule:"loc_f",m:"kuchnia|Case=Loc|Number=Sing"},
  {id:"d116",lvl:10,q:"Rozmawiam z ___.",base:"kelner",a:"kelnerem",de:"Ich spreche mit dem Kellner.",rule:"instr_mn",m:"kelner|Case=Ins|Number=Sing"},
  {id:"d117",lvl:10,q:"Podaj ___ pieprz.",base:"sie",a:"jej",de:"Gib ihr den Pfeffer.",rule:"dat_pron",m:"on|Case=Dat|Gender=Fem"},
  {id:"d118",lvl:10,q:"Wczoraj ___ kapustę.",base:"kupić · ich (Frau)",a:"kupiłam",de:"Gestern habe ich Kohl gekauft.",rule:"past_1",m:"kupić|Tense=Past|Number=Sing|Gender=Fem|Person=1"},
  {id:"d119",lvl:10,q:"Jutro ___ wino.",base:"otworzyć · ich",a:"otworzę",de:"Morgen öffne ich den Wein.",rule:"fut_pf",m:"otworzyć|Aspect=Perf|Person=1|Number=Sing|Tense=Fut|VerbForm=Fin"},
  {id:"d120",lvl:10,q:"Robię pięć ___.",base:"kanapka",a:"kanapek",de:"Ich mache fünf belegte Brote.",rule:"gen_pl_fn",m:"kanapka|Case=Gen|Number=Plur"},
  {id:"d121",lvl:10,q:"Lubię ___.",base:"kapusta",a:"kapustę",de:"Ich mag Kohl.",rule:"acc_f",m:"kapusta|Case=Acc|Number=Sing"},
  {id:"d122",lvl:10,q:"Rozmawiamy o ___.",base:"śniadanie",a:"śniadaniu",de:"Wir reden über das Frühstück.",rule:"loc_mn",m:"śniadanie|Case=Loc|Number=Sing"},
  {id:"d123",lvl:10,q:"Ty ___ herbatę?",base:"słodzić · du",a:"słodzisz",de:"Süßt du den Tee?",rule:"praes_i",m:"słodzić|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d124",lvl:10,q:"Ona ___ lodówkę.",base:"otwierać · sie",a:"otwiera",de:"Sie öffnet den Kühlschrank.",rule:"praes_am",m:"otwierać|Person=3|Number=Sing|Tense=Pres|VerbForm=Fin"},
  {id:"d125",lvl:10,q:"Dlaczego ___ wodę?",base:"wylewać · du",a:"wylewasz",de:"Warum gießt du das Wasser weg?",rule:"praes_am",m:"wylewać|Person=2|Number=Sing|Tense=Pres|VerbForm=Fin"}
]
});
